### ISSUE TITLE
Signed Exchange Gotchas

### ISSUE THREAD

**Issue by sleevi** [krgovind/first-party-sets#2]
While this explainer keeps it very high-level, thankfully, one concern around the [Signed Exchanges proposal](https://github.com/mikewest/first-party-sets/blob/361eeae8468d849ba1399a80c8bc6aa061561ea1/README.md#signed-exchanges) is that it would seem to require that `a.example` track and be constantly updating the SXGs for `b.example` and `c.example` in order to achieve the desired "no connection" property.

That is, while an SXG has a `validityUrl` that allows a U-A to continue to verify that the signing origin (`b.example`) is still attesting the thing it's attesting, that requires a U-A to fetch the validityUrl if the bundled-in proof (timestamp, OCSP response, CT evidence) is expired. In order to achieve the no-connection, the SXG served by `a.example` needs to be valid at time of serving to be used without a connection to `b.example`; this means that `a.example` will constantly need to be incorporating updates from the validityUrl into the resource it is hosting.

Similarly, `a.example` would have to be sensitive for the cache timing of the SXGs, to ensure that the physical URL is not cached for longer than the SXG is valid for.

The failure mode of this complexity is that it would merely devolve back to the original [proposal](https://github.com/mikewest/first-party-sets/blob/361eeae8468d849ba1399a80c8bc6aa061561ea1/README.md#a-proposal) - requiring a connection to `b.example` and `c.example` to fetch fresh proofs (if they can be obtained).

I mention this to suggest that, while SXGs may work, given the complexity, it seems very difficult for developers to get right, and would require constant and active infrastructure to maintain, constantly redeploying assets to ensure the SXGs function. This suggests that the simpler, original proposal may be more effective for user agents and developers.

**Comment by krgovind** [comment]
Our revised version of this proposal no longer relies on Signed Exchanges, so I am closing this issue.
